//@ts-ignore
import { dListOfPasswordHash } from "./migrationSchema";
import data = require("./password-hash.json");

export const setup: dListOfPasswordHash = {
  "primr-exp": { ...data["primr-exp"] },
  "app-takeoff": { ...data["app-takeoff"] },
  "app-takeoff-team": { ...data["app-takeoff-team"] },
  "arrizon-hierarchy": { ...data["arrizon-hierarchy"] },
  "barragan-familia-apptakeoff": { ...data["barragan-familia-apptakeoff"] },
  "benitez-rising-stars": { ...data["benitez-rising-stars"] },
  "big-apptakeoff": { ...data["big-apptakeoff"] },
  "brix-realty-apptakeoff": { ...data["brix-realty-apptakeoff"] },
  "carreon-hierarchy-mb2": { ...data["carreon-hierarchy-mb2"] },
  "casper-apptakeoff": { ...data["casper-apptakeoff"] },
  "chamorro-hierarchy-apptakeoff": { ...data["chamorro-hierarchy-apptakeoff"] },
  "champnation-apptakeoff": { ...data["champnation-apptakeoff"] },
  "corporateraiders-apptakeoff": { ...data["corporateraiders-apptakeoff"] },
  "crusaders-app-apptakeoff": { ...data["crusaders-app-apptakeoff"] },
  "david-and-associates": { ...data["david-and-associates"] },
  "dominators-mier-hierarchy": { ...data["dominators-mier-hierarchy"] },
  //Landmark Expansion = dream-team-apptakeoff
  "dream-team-apptakeoff": { ...data["dream-team-apptakeoff"] },
  "dream-team-drake": { ...data["dream-team-drake"] },
  "dream-team-hierarchy": { ...data["dream-team-hierarchy"] },
  "elite-apptakeoff": { ...data["elite-apptakeoff"] },
  "fearless-apptakeoff": { ...data["fearless-apptakeoff"] },
  "fletcher-team-apptakeoff": { ...data["fletcher-team-apptakeoff"] },
  "flight-apptakeoff": { ...data["flight-apptakeoff"] },
  "flores-fanatics": { ...data["flores-fanatics"] },
  "freedom-fighters-apptakeoff": { ...data["freedom-fighters-apptakeoff"] },
  "freedom-fighters-divita": { ...data["freedom-fighters-divita"] },
  "freedom-force-apptakeoff": { ...data["freedom-force-apptakeoff"] },
  "gladiators-apptakeoff": { ...data["gladiators-apptakeoff"] },
  "huffmans-heroes": { ...data["huffmans-heroes"] },
  "huge-apptakeoff": { ...data["huge-apptakeoff"] },
  "iron-life-apptakeoff": { ...data["iron-life-apptakeoff"] },
  "kingsqueens-apptakeoff": { ...data["kingsqueens-apptakeoff"] },
  "landrum-international": { ...data["landrum-international"] },
  landrumlegends: { ...data["landrumlegends"] },
  "lashner-lightning": { ...data["lashner-lightning"] },
  "legacy-builders-financial": { ...data["legacy-builders-financial"] },
  "legacybuilders-apptakeoff": { ...data["legacybuilders-apptakeoff"] },
  "legacyoflegends-apptakeoff": { ...data["legacyoflegends-apptakeoff"] },
  "level-up-hierarchy-apptakeoff": { ...data["level-up-hierarchy-apptakeoff"] },
  "limitless-apptakeoff": { ...data["limitless-apptakeoff"] },
  "lion-chasers-apptakeoff": { ...data["lion-chasers-apptakeoff"] },
  "millertime-apptakeoff": { ...data["millertime-apptakeoff"] },
  "mitchell-miracle-makers": { ...data["mitchell-miracle-makers"] },
  "never-tolerate-average": { ...data["never-tolerate-average"] },
  "nextlevel-apptakeoff": { ...data["nextlevel-apptakeoff"] },
  "one-team-one-dream-apptakeoff": { ...data["one-team-one-dream-apptakeoff"] },
  "one-team-one-dream": { ...data["one-team-one-dream"] },
  "peak-achievers": { ...data["peak-achievers"] },
  "persistence-apptakeoff": { ...data["persistence-apptakeoff"] },
  "powerbuilders-apptakeoff": { ...data["powerbuilders-apptakeoff"] },
  "powerteam-apptakeoff": { ...data["powerteam-apptakeoff"] },
  "preloaded-primerica-content": { ...data["preloaded-primerica-content"] },
  "protectors-apptakeoff": { ...data["protectors-apptakeoff"] },
  "quiet-storm-apptakeoff": { ...data["quiet-storm-apptakeoff"] },
  "rumble-apptakeof": { ...data["rumble-apptakeof"] },
  "run-fields": { ...data["run-fields"] },
  "rvp-builders-apptakeoff": { ...data["rvp-builders-apptakeoff"] },
  "sabia-apptakeoff": { ...data["sabia-apptakeoff"] },
  "sanders-crusade-nation": { ...data["sanders-crusade-nation"] },
  shepardsuperteam: { ...data["shepardsuperteam"] },
  "summit-apptakeoff": { ...data["summit-apptakeoff"] },
  "super-saints": { ...data["super-saints"] },
  "superbase-cd4c1": { ...data["superbase-cd4c1"] },
  "team-action-crusaders": { ...data["team-action-crusaders"] },
  "team-canada-apptakeoff": { ...data["team-canada-apptakeoff"] },
  "team-diehl-apptakeoff": { ...data["team-diehl-apptakeoff"] },
  "team-hughes-all-in": { ...data["team-hughes-all-in"] },
  "team-impact-2f2f0": { ...data["team-impact-2f2f0"] },
  "team-rhino-apptakeoff": { ...data["team-rhino-apptakeoff"] },
  "teamofdestiny-apptakeoff": { ...data["teamofdestiny-apptakeoff"] },
  "team-impact-gilia-apptakeoff": { ...data["team-impact-gilia-apptakeoff"] },
  "team-vip-apptakeoff": { ...data["team-vip-apptakeoff"] },
  "team-lavination-apptakeoff": { ...data["team-lavination-apptakeoff"] },
  "team-legacy-apptakeoff": { ...data["team-legacy-apptakeoff"] },
  "team-tenacious-apptakeoff": { ...data["team-tenacious-apptakeoff"] },
  "team-unstoppable-apptakeoff": { ...data["team-unstoppable-apptakeoff"] },
  "team-xplosion-apptakeoff": { ...data["team-xplosion-apptakeoff"] },
  "the-global-alliance-apptakeoff": {
    ...data["the-global-alliance-apptakeoff"],
  },
  "thechargingrhinos-apptakeoff": { ...data["thechargingrhinos-apptakeoff"] },
  "thestandard-apptakeoff": { ...data["thestandard-apptakeoff"] },
  "trendsetters-apptakeoff": { ...data["trendsetters-apptakeoff"] },
  "thetroopnation-apptakeoff": { ...data["thetroopnation-apptakeoff"] },
  "tu-empire-builders": { ...data["tu-empire-builders"] },
  "visionaries-apptakeoff": { ...data["visionaries-apptakeoff"] },
  "wealth-builders-apptakeoff": { ...data["wealth-builders-apptakeoff"] },
  "world-changers-west-apptakeoff": {
    ...data["world-changers-west-apptakeoff"],
  },
  "world-changers-apptakeoff": { ...data["world-changers-apptakeoff"] },
  "wyd1-apptakeoff": { ...data["wyd1-apptakeoff"] },
  "xtreme-nation": { ...data["xtreme-nation"] },
  "vangoor-apptakeoff": { ...data["vangoor-apptakeoff"] },
  "clone-apptakeoff": { ...data["clone-apptakeoff"] },
};
